name: gpu-test
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deployment:
    name: 'self-hosted'
    runs-on: self-hosted
    steps:
      - name: Pull
        working-directory: /home/ubuntu/stable-diffusion-webui
        run: git pull
      - name: Start server
        run: sudo nohup $(which python) webui.py >out.log 2>out.err < /dev/null &
